# Generated by Django 3.2 on 2022-05-07 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walaka_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('national_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alt_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_id', models.CharField(blank=True, max_length=20, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('map_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.CharField(blank=True, max_length=1000, null=True)),
                ('longitude', models.CharField(blank=True, max_length=1000, null=True)),
                ('non_schooling', models.CharField(blank=True, max_length=1000, null=True)),
                ('primary_dependants', models.CharField(blank=True, max_length=1000, null=True)),
                ('secondary_dependants', models.CharField(blank=True, max_length=1000, null=True)),
                ('tertiary_dependants', models.CharField(blank=True, max_length=1000, null=True)),
                ('guarantors_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantors_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantors_relation', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_membership_fee', models.BooleanField(default=False)),
                ('working_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('bussiness_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('bussiness_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('residence_town', models.CharField(blank=True, max_length=1000, null=True)),
                ('estimate_building', models.CharField(blank=True, max_length=1000, null=True)),
                ('street_house_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('bussiness_age', models.CharField(blank=True, max_length=1000, null=True)),
                ('bussiness_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('loan_security', models.CharField(blank=True, max_length=1000, null=True)),
                ('good_day', models.IntegerField(blank=True, null=True)),
                ('bad_day', models.IntegerField(blank=True, null=True)),
                ('days_per_week', models.IntegerField(blank=True, null=True)),
                ('stock_purchase', models.IntegerField(blank=True, null=True)),
                ('transport', models.IntegerField(blank=True, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('other_expenses', models.IntegerField(blank=True, null=True)),
                ('avatar1', models.ImageField(upload_to='')),
                ('avatar2', models.ImageField(upload_to='')),
                ('avatar3', models.ImageField(upload_to='')),
                ('avatar4', models.ImageField(upload_to='')),
                ('avatar5', models.ImageField(upload_to='')),
                ('front_id_image', models.ImageField(upload_to='')),
                ('back_id_image', models.ImageField(upload_to='')),
                ('files', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Borrowers',
                'verbose_name_plural': 'Borrowers',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200)),
                ('branch_location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('map_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.CharField(blank=True, max_length=1000, null=True)),
                ('longitude', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Loan Officer', 'Loan Officer'), ('Loan Collection Officer', 'Loan Collection Officer'), ('Loan Verification Officer', 'Loan Verification Officer')], max_length=100)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(upload_to='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Loanapp.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfiles',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('referee_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('referee_relation', models.CharField(blank=True, max_length=200, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantors_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantors_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantors_relation', models.CharField(blank=True, max_length=200, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=20000, null=True)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrowers',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Loanapp.branch'),
        ),
        migrations.AddField(
            model_name='borrowers',
            name='loan_collection_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_collection_officer', to='Loanapp.userprofiles'),
        ),
        migrations.AddField(
            model_name='borrowers',
            name='loan_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_officer', to='Loanapp.userprofiles'),
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers')),
            ],
        ),
    ]
