# Generated by Django 3.2 on 2022-05-30 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Loanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=20000)),
                ('note_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=20000, null=True)),
                ('commented_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_amount', models.FloatField(default=0, max_length=10000)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('remaining_amount', models.FloatField(default=0)),
                ('fully_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Installments',
                'verbose_name_plural': 'Installments',
            },
        ),
        migrations.CreateModel(
            name='LoanNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=20000)),
                ('note_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanOverpayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_amount', models.FloatField(max_length=200000)),
                ('loan_percentage', models.CharField(max_length=2000)),
                ('period', models.CharField(max_length=20000)),
                ('total_loan', models.FloatField(max_length=200000)),
                ('payment_type', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount_paid', models.FloatField(default=0, max_length=10000)),
                ('amount_remain', models.FloatField(default=0, max_length=10000)),
                ('loan_purpose1', models.CharField(blank=True, max_length=20000, null=True)),
                ('loan_purpose2', models.CharField(blank=True, max_length=20000, null=True)),
                ('loan_purpose3', models.CharField(blank=True, max_length=20000, null=True)),
                ('loan_purpose4', models.CharField(blank=True, max_length=20000, null=True)),
                ('status', models.CharField(default='NEW', max_length=200)),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('denied_at', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('disbursed_at', models.DateField(blank=True, null=True)),
                ('startpayment_at', models.DateField(blank=True, null=True)),
                ('endpayment_at', models.DateField(blank=True, null=True)),
                ('fully_paid_on', models.DateField(blank=True, null=True)),
                ('balance_today', models.FloatField(blank=True, max_length=200000, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loans',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.CreateModel(
            name='MembershipFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('amount', models.CharField(default=500, max_length=300)),
            ],
            options={
                'verbose_name': 'MembershipFees',
                'verbose_name_plural': 'MembershipFeess',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.loans')),
            ],
        ),
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name': 'Assets', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='guarantors',
            options={'verbose_name': 'Guarantors', 'verbose_name_plural': 'Guarantors'},
        ),
        migrations.AlterModelOptions(
            name='referees',
            options={'verbose_name': 'Referees', 'verbose_name_plural': 'Referees'},
        ),
        migrations.RemoveField(
            model_name='borrowers',
            name='avatar1',
        ),
        migrations.RemoveField(
            model_name='borrowers',
            name='avatar2',
        ),
        migrations.RemoveField(
            model_name='borrowers',
            name='avatar3',
        ),
        migrations.RemoveField(
            model_name='borrowers',
            name='avatar4',
        ),
        migrations.RemoveField(
            model_name='borrowers',
            name='avatar5',
        ),
        migrations.RemoveField(
            model_name='borrowers',
            name='guarantors_contact',
        ),
        migrations.RemoveField(
            model_name='borrowers',
            name='guarantors_full_name',
        ),
        migrations.RemoveField(
            model_name='borrowers',
            name='guarantors_relation',
        ),
        migrations.AddField(
            model_name='borrowers',
            name='disbursment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrowers',
            name='registerd_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='inserted_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='non_schooling',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='primary_dependants',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='secondary_dependants',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='tertiary_dependants',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='membershipfees',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers'),
        ),
        migrations.AddField(
            model_name='loans',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers'),
        ),
        migrations.AddField(
            model_name='loans',
            name='denied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denied_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loans',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.loans'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='tied_installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.installments'),
        ),
        migrations.AddField(
            model_name='loanoverpayments',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers'),
        ),
        migrations.AddField(
            model_name='loannotes',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.loans'),
        ),
        migrations.AddField(
            model_name='loannotes',
            name='notemadeby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installments',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.loans'),
        ),
        migrations.AddField(
            model_name='comments',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers'),
        ),
        migrations.AddField(
            model_name='comments',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowernotes',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers'),
        ),
        migrations.AddField(
            model_name='borrowernotes',
            name='notemadeby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avatarimages',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.borrowers'),
        ),
    ]
