# Generated by Django 3.2 on 2022-05-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0002_auto_20220530_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_full_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='value',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='address',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='alt_phone_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='first_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='gender',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='last_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='marital_status',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='national_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='next_of_kin_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='nickname',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_location',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='guarantors',
            name='guarantors_contact',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='guarantors',
            name='guarantors_full_name',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='guarantors',
            name='guarantors_relation',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='installments',
            name='installment_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_percentage',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='membershipfees',
            name='amount',
            field=models.CharField(default=500, max_length=30000),
        ),
        migrations.AlterField(
            model_name='referees',
            name='referee_contact',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='referees',
            name='referee_full_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='referees',
            name='referee_relation',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='email_address',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='first_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='last_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='phone_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
