# Generated by Django 3.2 on 2022-05-31 13:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0003_auto_20220531_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
