# Generated by Django 3.2 on 2022-05-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0004_auto_20220531_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfees',
            name='amount',
            field=models.FloatField(default=500, max_length=30000),
        ),
    ]
