# Generated by Django 3.2 on 2022-06-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0006_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowers',
            name='gen_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
