# Generated by Django 3.2 on 2022-06-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0007_borrowers_gen_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='penalty',
            field=models.FloatField(default=0, max_length=2000),
        ),
    ]
