# Generated by Django 3.2 on 2022-06-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0008_loans_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='run_penalty_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
